urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views

app_name = 'files'

urlpatterns = [
        path('index', views.index, name='index'),
        path('authenticateuser', views.authenticate_user, name='authenticateuser'),
		path('downloadfile/<int:user_id>/<int:content_id>', views.download_file, name='downloadfile'),
        path('logoutwebcut', views.logout_webcut, name='logoutwebcut'),
        path('listuploadedfiles', views.list_uploaded_files, name='listuploadedfiles'),
        ]

models.py
from django.db import models
from datetime import datetime, timedelta
from django.contrib.auth.models import User
from files import settings as files_settings

# Models
	
def user_path_file(instance_content, empty_parameter):
	return '{0}/{1}/{2}'.format(files_settings.FILES_ROOT, instance_content.user.id, instance_content.file.name)

class Content(models.Model):
	user = models.ForeignKey(User, on_delete = models.CASCADE)
	file = models.FileField(upload_to = user_path_file, max_length = 100) 
	date_time = models.DateTimeField(auto_now = True)
	date_time_delete = models.DateTimeField(default = datetime.now() + timedelta(days = 5))

	def __str__(self):
		return str(self.file.name)

# Functions

def find_or_create_user(request):
	try:
		user = User.objects.get(username = request.user)
	except User.DoesNotExist:
		user = User.objects.create_user(username = request.POST.get('username'), password = request.POST.get('password'))
		user.save()
	finally:
		return user

def save_user_file(request, user):
		user_file = Content(user = user, file = request.FILES.get('filename'), date_time_delete = datetime.now() + timedelta(days = 180))
		user_file.save()

def user_contents(request):
	try:
		user = User.objects.get(username = request.user)
		contents = user.content_set.all()
		return contents

	except User.DoesNotExist:
		return  None

def user_content(user_id, content_id):
	try:
		user = User.objects.get(id = user_id)
		content = user.content_set.get(id = content_id)
		return content

	except User.DoesNotExist:
		return None

def create_user(request):
	user = User.objects.create_user(username = request.POST.get('username'), password = request.POST.get('password'))
	user.save()
	return user

forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from files.models import User

#class IdentifierData(forms.Form):
#    identifier = forms.CharField(label = ' Identifier ', max_length = 100)
#    code = forms.CharField(label = ' Code ', max_length = 100)

class IdentifierData(forms.ModelForm):
	class Meta:
		model = User
		fields = ['username', 'password']

		labels = {
			'username': _('Identifier'),
			'password': _('Code'),	
		}

		help_texts = {
			'username': _(''),
		}
		

views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout

from files.forms import IdentifierData
from files.models import save_user_file, user_content, user_contents, find_or_create_user
from django.conf import settings

import magic
import os

# Create your views here.

def index(request):
	return send_identifer_form(request)

def logout_webcut(request):
	logout(request)
	return redirect('files:index')

def upload_file_successful(request):
	return render(request, 'files/upload_file_successful.html')

def form_data_not_valid(request): #, errors):
	return render(request, 'files/form_data_not_valid.html') #, {'errors': errors}) 

def identifier_not_register(request):
	return render(request, 'files/identifier_not_register.html')

def list_uploaded_files(request):
	contents = user_contents(request)
	if contents: 
		# Override content.file.name
		for content in contents:
			content.file.name = os.path.split(content.file.name)[1]
		return render(request, 'files/list_uploaded_files.html', {'contents': contents})
	else:
		return render(request, 'files/download_files_not_exist.html')	

def download_file(request, user_id, content_id):
	content = user_content(user_id, content_id)
	if content and request.user.id == user_id and request.user.is_authenticated:
		path_to_file = settings.MEDIA_ROOT + content.file.url
		content.file.open()
		response = HttpResponse(content.file.read(), content_type = magic.from_file(path_to_file, mime = True))
		response['Content-Disposition'] = 'attachment; filename="{filename}"'.format(filename = os.path.split(content.file.url)[1])
		response['Content-Length'] = content.file.size
		return response
	else:
		return redirect('files:index')

def send_identifer_form(request):
	return render(request, 'files/index.html', {'form': IdentifierData, 'request': request})

def action_file(request):
	if request.method == 'POST':
		if request.POST.get('upload') != None and len(request.FILES) > 0: 
			save_user_file(request, find_or_create_user(request))
			return upload_file_successful(request)
		elif request.POST.get('download') != None:
			return list_uploaded_files(request) 
		else:
			return render(request, 'files/empty_files.html')
	else:
		return send_identifer_form(request)

def authenticate_user(request):
	if not request.user.is_authenticated:
		user = authenticate(request, username = request.POST.get('username'), password = request.POST.get('password'))
		if user is not None:
			login(request, user)
			return action_file(request)
		else:
			form = IdentifierData(request.POST)
			if form.is_valid():
				if request.POST.get('newidentifier') != None:
					user = find_or_create_user(request)
					login(request, user)
					return action_file(request)
				else:
					return identifier_not_register(request)
			else:
				print(form.errors)
				return form_data_not_valid(request) #, form.errors)
	else:
		return action_file(request)

templates/files/download_files_not_exist.html
<h1> Files not exist </h1>
<div>
<p><a href = "{% url 'files:index' %}"> upload file </a></p>
</div>

templates/files/empty_files.html
<h1> File not select </h1>
<div>
<p><a href = "{% url 'files:index' %}"> upload file </a></p>
</div>

templates/files/form_data_not_valid.html
<h1> Form data NOT valid.</h1>
<div>
<p><a href = "{% url 'files:index' %}"> upload file </a></p>
{# {{ errors }} #}
</div>

templates/files/identifier_not_register.html
<h1> Identifier not register </h1>
<div>
<p><a href = "{% url 'files:index' %}"> upload file </a></p>
</div>

templates/files/index.html
{% load static %}

<h1> webcut</h1>
<form action="{% url 'files:authenticateuser' %}" method='post' enctype='multipart/form-data'>
{% csrf_token %}
{% if not request.user.is_authenticated %}
{{ form.as_p }}
<input type="checkbox" name="newidentifier" value="registration"> Register new Identifier <br>
{% else %}
<p><a href = "{% url 'files:logoutwebcut' %}"> logout </a></p>
{% endif %}
{{ request.user.username }}
<p><p><input type='file' name='filename'></p>
<div>
<p><input type='submit' name='upload' value='Upload'></p></p>
</div>
<div>
<p><input type='submit' name='download' value='Download'></p>
</div>
</form>

templates/files/list_download_files.html
<h1> webcut</h1>
<h3> download file</h3>
{% for content in contents %}
<p><a href = {% url 'files:downloadfile' user_id=content.user.id content_id=content.id %}>  {{ content.file.name }} </a>
  ---  {{ content.date_time|date:'d.m.Y' }} --- {{ content.date_time_delete|date:'d.m.Y' }} </p>
{% endfor %}

templates/files/list_uploaded_files.html
<h1> webcut</h1>
<h3> download file</h3>
<p><a href = "{% url 'files:index' %}"> upload file </a></p>
{% for content in contents %}
<p><a href = {% url 'files:downloadfile' user_id=content.user.id content_id=content.id %}>  {{ content.file.name }} </a>
  ---  {{ content.date_time|date:'d.m.Y' }} --- {{ content.date_time_delete|date:'d.m.Y' }} </p>
{% endfor %}

templates/files/upload_file_successful.html
<h1> successful upload</h1>
<div>
<p><a href = "{% url 'files:index' %}"> upload file </a></p>
<p><a href = "{% url 'files:listuploadedfiles' %}"> list files </a></p>
</div>

templates/files/upload_file_unsuccessful.html
<h1> UNsuccessful upload. Form data NOT valid.</h1>
<div>
<p><a href = "{% url 'files:index' %}"> upload file </a></p>
</div>